apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: tasker-app-alerts
  namespace: monitoring
  labels:
    app.kubernetes.io/name: tasker-app
    app.kubernetes.io/part-of: tasker-platform
    prometheus: kube-prometheus
    role: alert-rules
spec:
  groups:
    - name: tasker-app.alerts
      rules:
        - alert: TaskerAppHighCpuUsage
          expr: sum(rate(container_cpu_usage_seconds_total{namespace="default", pod=~"tasker-app.*"}[5m])) by (pod) > 0.5
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Высокое использование CPU в Tasker App"
            description: "Pod {{ $labels.pod }} использует CPU > 50% более 5 минут."

        - alert: TaskerAppHighMemoryUsage
          expr: sum(container_memory_working_set_bytes{namespace="default", pod=~"tasker-app.*"}) by (pod) / sum(container_spec_memory_limit_bytes{namespace="default", pod=~"tasker-app.*"}) by (pod) > 0.8
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Высокое использование памяти в Tasker App"
            description: "Pod {{ $labels.pod }} использует память > 80% более 5 минут."

        - alert: TaskerAppHighErrorRate
          expr: sum(rate(http_server_requests_seconds_count{namespace="default", status=~"5.."}[5m])) / sum(rate(http_server_requests_seconds_count{namespace="default"}[5m])) > 0.05
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "Высокий уровень ошибок в Tasker App"
            description: "Более 5% запросов завершаются с ошибкой (HTTP 5xx) в течение 2 минут."

        - alert: TaskerAppSlowResponses
          expr: histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{namespace="default"}[5m])) by (le)) > 0.5
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Медленные ответы Tasker App"
            description: "95-й процентиль времени отклика превышает 500 мс в течение 5 минут."
