apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tasker-app
  namespace: tasker
  labels:
    app.kubernetes.io/instance: tasker-app
    app.kubernetes.io/name: tasker-app
    release: prometheus
spec:
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 14s
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: (jvm_memory_used_bytes|process_cpu_usage|http_server_requests_seconds_count|system_cpu_usage|jvm_gc_pause_seconds_count|jvm_memory_committed_bytes|jvm_threads_live|hikaricp_connections_active|hikaricp_connections_usage|tasker_tasks_total|tasker_tasks_completed_total)
          action: keep
  selector:
    matchLabels:
      app.kubernetes.io/instance: tasker-app
      app.kubernetes.io/name: tasker-app
